# Generated by Django 5.2.7 on 2025-10-19 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbot', '0001_initial'),
        ('manuals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PIClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intrinsic_product', models.CharField(blank=True, max_length=255, null=True)),
                ('extrinsic_product', models.CharField(blank=True, max_length=255, null=True)),
                ('intrinsic_information', models.CharField(blank=True, max_length=255, null=True)),
                ('extrinsic_information', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='manuals.manual')),
                ('query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pi_classifications', to='chatbot.chatquery')),
            ],
        ),
    ]
