# Generated by Django 5.2.7 on 2025-10-18 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manuals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('user_type', models.CharField(choices=[('technician', 'Technician'), ('user', 'Common User')], default='user', max_length=50)),
                ('response_text', models.TextField(blank=True, null=True)),
                ('uml_code', models.TextField(blank=True, null=True)),
                ('diagram_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manuals.manual')),
            ],
        ),
    ]
