# Generated by Django 5.2.7 on 2025-10-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatquery',
            name='feedback',
            field=models.CharField(blank=True, default='Good', max_length=10, null=True),
        ),
    ]
