# Generated by Django 5.2.7 on 2025-10-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatquery_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatquery',
            name='puml_file',
            field=models.FileField(blank=True, null=True, upload_to='uml_code/'),
        ),
        migrations.AddField(
            model_name='chatquery',
            name='py_file',
            field=models.FileField(blank=True, null=True, upload_to='uml_code_py/'),
        ),
        migrations.AddField(
            model_name='chatquery',
            name='txt_file',
            field=models.FileField(blank=True, null=True, upload_to='uml_code_txt/'),
        ),
    ]
