# Generated by Django 5.2.7 on 2025-10-22 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chatquery_puml_file_chatquery_py_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatquery',
            name='puml_file',
        ),
        migrations.RemoveField(
            model_name='chatquery',
            name='py_file',
        ),
        migrations.RemoveField(
            model_name='chatquery',
            name='txt_file',
        ),
    ]
