# Generated by Django 5.2.7 on 2025-10-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_remove_chatquery_puml_file_remove_chatquery_py_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatquery',
            name='puml_file',
            field=models.FileField(blank=True, null=True, upload_to='uml_files/'),
        ),
        migrations.AddField(
            model_name='chatquery',
            name='py_file',
            field=models.FileField(blank=True, null=True, upload_to='uml_files/'),
        ),
        migrations.AddField(
            model_name='chatquery',
            name='txt_file',
            field=models.FileField(blank=True, null=True, upload_to='uml_files/'),
        ),
    ]
