# Generated by Django 5.2.7 on 2025-10-18 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manuals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_index', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField()),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('manual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='manuals.manual')),
            ],
        ),
    ]
